### ISSUE TITLE
image大于3

### ISSUE THREAD

**Issue by TrueloveSomeGIRl** [ye6fan/jmcomic#1]
image: ^4.1.0 # 在重构图片时使用，导包4.2.0会报错：rangeerror: value not in range: ${}+3

我用4.1.0 也是 大于三 你是怎么解决的大兄弟 
![image](https://github.com/user-attachments/assets/a6ccb0f7-3130-4508-a967-3707bccd3b67)

**Comment by ye6fan** [comment]
这个没有解决，只能用image: 4.1.7，这个固定版本了
